name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Update "v1" tag to point latest release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        with:
          ref: v1
          description: Major version v1 latest release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}