name: Sync with client repo
on: workflow_dispatch

jobs:
  sync-repos:
    name: Sync repos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action
      uses: "./"
      env:
        SRC_REPO: git@gitlab.com:neatbyte-solutions/action-git-copy-to-repo.git
        SRC_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SRC_BRANCH: main
        TARGET_REPO: NeatByte-Solutions/action-git-copy-to-repo
        TARGET_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TARGET_BRANCH: master
        DELETE_FROM_SRC: |
          NEATBYTE*
          .github/**
          known_hosts
        DELETE_FROM_TARGET: |
          .git/**
          NEATBYTE*
          .github/**
          known_hosts
        COMMIT_MESSAGE: 'some msg'
        COMMIT_AUTHOR: Vitalii
        COMMIT_AUTHOR_EMAIL: vitalii@gmail.com
        KNOWN_HOSTS_FILE: action/resources/known_hosts