name: Sync with client repo
on: workflow_dispatch

jobs:
  sync-repos:
    name: Sync repos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      env:
        SRC_SSH_REPO: git@gitlab.com:neatbyte-solutions/action-git-copy-to-repo.git
        SRC_SSH_PRIVATE_KEY: key
        SRC_BRANCH: main
        TARGET_GITHUB_REPO: NeatByte-Solutions/action-git-copy-to-repo
        TARGET_GITHUB_TOKEN: token
        TARGET_BRANCH: master